FROM oven/bun:1

WORKDIR /usr/src/app

# Copy root configs
COPY package.json ./
COPY bun.lock ./bun.lock
COPY turbo.json ./turbo.json

# Copy the monorepo structure (apps + packages)
COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN bun install

# Generate Prisma client
RUN cd packages/db && bun prisma generate


EXPOSE 8080

CMD ["bun", "run", "start:backend"]
